name: Update Trailhead Stats

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily
  workflow_dispatch:

jobs:
  trailhead-stats:
    name: Trailhead Stats
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get Trailhead stats
        id: trailhead-stats
        uses: nabondance/Trailhead-Stats@v2.0.0
        with:
          trailhead-username: manuelvillencano
          display-type: 'card'
          display-file: 'README.md'
          file-format: 'html'
          card-path: './TS-cards'
          show-certification-latest: 'visible'
          show-certification: 'visible'
